# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again. Do not edit this file unless you know what you are doing.

import os
import numpy as np

from PyQt6 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

from main import process_segment, process_segment_with_figure


class ResizableCanvas(FigureCanvas):
    def _sync_figure_to_canvas(self):
        fig = self.figure
        if fig is None:
            return

        dpi = fig.dpi
        scale = self.devicePixelRatioF() or 1.0
        w = max(self.width(), 1) * scale
        h = max(self.height(), 1) * scale

        fig.set_size_inches(w / dpi, h / dpi, forward=False)
        self.draw_idle()

    def resizeEvent(self, event):
        super().resizeEvent(event)
        self._sync_figure_to_canvas()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.main_window = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 650))

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)

        root_layout = QtWidgets.QHBoxLayout(self.centralwidget)
        root_layout.setContentsMargins(10, 10, 10, 10)
        root_layout.setSpacing(12)

        self.splitter = QtWidgets.QSplitter(QtCore.Qt.Orientation.Horizontal, self.centralwidget)
        self.splitter.setChildrenCollapsible(False)
        root_layout.addWidget(self.splitter)

        # Left side: metrics
        self.left_scroll = QtWidgets.QScrollArea()
        self.left_scroll.setWidgetResizable(True)
        self.left_scroll.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)

        self.left_panel = QtWidgets.QWidget()
        self.left_scroll.setWidget(self.left_panel)

        left_layout = QtWidgets.QVBoxLayout(self.left_panel)
        left_layout.setContentsMargins(8, 8, 8, 8)
        left_layout.setSpacing(12)

        self.metrics_title = QtWidgets.QLabel(parent=self.left_panel)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.metrics_title.setFont(font)
        self.metrics_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.metrics_title.setObjectName("metrics_title")
        left_layout.addWidget(self.metrics_title)

        line1 = QtWidgets.QFrame(parent=self.left_panel)
        line1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        line1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        left_layout.addWidget(line1)

        # ECG section
        self.ecg_section = QtWidgets.QFrame(parent=self.left_panel)
        ecg_layout = QtWidgets.QGridLayout(self.ecg_section)
        ecg_layout.setContentsMargins(0, 0, 0, 0)
        ecg_layout.setHorizontalSpacing(12)
        ecg_layout.setVerticalSpacing(8)
        ecg_layout.setColumnStretch(0, 1)
        ecg_layout.setColumnStretch(1, 0)

        self.ecg_title = QtWidgets.QLabel(parent=self.ecg_section)
        self.ecg_title.setFont(font)
        self.ecg_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ecg_title.setObjectName("ecg_title")

        self.ecg_heartrate_title = QtWidgets.QLabel(parent=self.ecg_section)
        self.ecg_heartrate_title.setFont(font)
        self.ecg_heartrate_title.setObjectName("ecg_heartrate_title")

        self.ecg_heartrate_value = QtWidgets.QLabel(parent=self.ecg_section)
        self.ecg_heartrate_value.setFont(font)
        self.ecg_heartrate_value.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.ecg_heartrate_value.setObjectName("ecg_heartrate_value")

        self.ecg_sqi_title = QtWidgets.QLabel(parent=self.ecg_section)
        self.ecg_sqi_title.setFont(font)
        self.ecg_sqi_title.setObjectName("ecg_sqi_title")

        self.ecg_sqi_value = QtWidgets.QLabel(parent=self.ecg_section)
        self.ecg_sqi_value.setFont(font)
        self.ecg_sqi_value.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.ecg_sqi_value.setObjectName("ecg_sqi_value")

        self.ecg_weight_title = QtWidgets.QLabel(parent=self.ecg_section)
        self.ecg_weight_title.setFont(font)
        self.ecg_weight_title.setObjectName("ecg_weight_title")

        self.ecg_weight_value = QtWidgets.QLabel(parent=self.ecg_section)
        self.ecg_weight_value.setFont(font)
        self.ecg_weight_value.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.ecg_weight_value.setObjectName("ecg_weight_value")

        ecg_layout.addWidget(self.ecg_title, 0, 0, 1, 2)
        ecg_layout.addWidget(self.ecg_heartrate_title, 1, 0)
        ecg_layout.addWidget(self.ecg_heartrate_value, 1, 1)
        ecg_layout.addWidget(self.ecg_sqi_title, 2, 0)
        ecg_layout.addWidget(self.ecg_sqi_value, 2, 1)
        ecg_layout.addWidget(self.ecg_weight_title, 3, 0)
        ecg_layout.addWidget(self.ecg_weight_value, 3, 1)

        left_layout.addWidget(self.ecg_section)

        line2 = QtWidgets.QFrame(parent=self.left_panel)
        line2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        line2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        left_layout.addWidget(line2)

        # PPG section
        self.ppg_section = QtWidgets.QFrame(parent=self.left_panel)
        ppg_layout = QtWidgets.QGridLayout(self.ppg_section)
        ppg_layout.setContentsMargins(0, 0, 0, 0)
        ppg_layout.setHorizontalSpacing(12)
        ppg_layout.setVerticalSpacing(8)
        ppg_layout.setColumnStretch(0, 1)
        ppg_layout.setColumnStretch(1, 0)

        self.ppg_title = QtWidgets.QLabel(parent=self.ppg_section)
        self.ppg_title.setFont(font)
        self.ppg_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ppg_title.setObjectName("ppg_title")

        self.ppg_heartrate_title = QtWidgets.QLabel(parent=self.ppg_section)
        self.ppg_heartrate_title.setFont(font)
        self.ppg_heartrate_title.setObjectName("ppg_heartrate_title")

        self.ppg_heartrate_value = QtWidgets.QLabel(parent=self.ppg_section)
        self.ppg_heartrate_value.setFont(font)
        self.ppg_heartrate_value.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.ppg_heartrate_value.setObjectName("ppg_heartrate_value")

        self.ppg_sqi_title = QtWidgets.QLabel(parent=self.ppg_section)
        self.ppg_sqi_title.setFont(font)
        self.ppg_sqi_title.setObjectName("ppg_sqi_title")

        self.ppg_sqi_value = QtWidgets.QLabel(parent=self.ppg_section)
        self.ppg_sqi_value.setFont(font)
        self.ppg_sqi_value.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.ppg_sqi_value.setObjectName("ppg_sqi_value")

        self.ppg_weight_title = QtWidgets.QLabel(parent=self.ppg_section)
        self.ppg_weight_title.setFont(font)
        self.ppg_weight_title.setObjectName("ppg_weight_title")

        self.ppg_weight_value = QtWidgets.QLabel(parent=self.ppg_section)
        self.ppg_weight_value.setFont(font)
        self.ppg_weight_value.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.ppg_weight_value.setObjectName("ppg_weight_value")

        ppg_layout.addWidget(self.ppg_title, 0, 0, 1, 2)
        ppg_layout.addWidget(self.ppg_heartrate_title, 1, 0)
        ppg_layout.addWidget(self.ppg_heartrate_value, 1, 1)
        ppg_layout.addWidget(self.ppg_sqi_title, 2, 0)
        ppg_layout.addWidget(self.ppg_sqi_value, 2, 1)
        ppg_layout.addWidget(self.ppg_weight_title, 3, 0)
        ppg_layout.addWidget(self.ppg_weight_value, 3, 1)

        left_layout.addWidget(self.ppg_section)

        line3 = QtWidgets.QFrame(parent=self.left_panel)
        line3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        line3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        left_layout.addWidget(line3)

        # FHR section
        self.fhr_section = QtWidgets.QFrame(parent=self.left_panel)
        fhr_layout = QtWidgets.QGridLayout(self.fhr_section)
        fhr_layout.setContentsMargins(0, 0, 0, 0)
        fhr_layout.setHorizontalSpacing(12)
        fhr_layout.setVerticalSpacing(8)
        fhr_layout.setColumnStretch(0, 1)
        fhr_layout.setColumnStretch(1, 0)

        self.fused_title = QtWidgets.QLabel(parent=self.fhr_section)
        self.fused_title.setFont(font)
        self.fused_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.fused_title.setObjectName("fused_title")

        self.fhr_title = QtWidgets.QLabel(parent=self.fhr_section)
        self.fhr_title.setFont(font)
        self.fhr_title.setObjectName("fhr_title")

        self.fhr_value = QtWidgets.QLabel(parent=self.fhr_section)
        self.fhr_value.setFont(font)
        self.fhr_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.fhr_value.setObjectName("fhr_value")

        self.fhrvsdnn_title = QtWidgets.QLabel(parent=self.fhr_section)
        self.fhrvsdnn_title.setFont(font)
        self.fhrvsdnn_title.setObjectName("fhrvsdnn_title")

        self.fhrvsdnn_value = QtWidgets.QLabel(parent=self.fhr_section)
        self.fhrvsdnn_value.setFont(font)
        self.fhrvsdnn_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.fhrvsdnn_value.setObjectName("fhrvsdnn_value")

        self.fhrvrmssd_title = QtWidgets.QLabel(parent=self.fhr_section)
        self.fhrvrmssd_title.setFont(font)
        self.fhrvrmssd_title.setObjectName("fhrvrmssd_title")

        self.fhrvrmssd_value = QtWidgets.QLabel(parent=self.fhr_section)
        self.fhrvrmssd_value.setFont(font)
        self.fhrvrmssd_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.fhrvrmssd_value.setObjectName("fhrvrmssd_value")

        fhr_layout.addWidget(self.fused_title, 0, 0, 1, 2)

        fhr_layout.addWidget(self.fhr_title, 1, 0)
        fhr_layout.addWidget(self.fhr_value, 1, 1)
        fhr_layout.addWidget(self.fhrvsdnn_title, 2, 0)
        fhr_layout.addWidget(self.fhrvsdnn_value, 2, 1)
        fhr_layout.addWidget(self.fhrvrmssd_title, 3, 0)
        fhr_layout.addWidget(self.fhrvrmssd_value, 3, 1)

        left_layout.addWidget(self.fhr_section)
        left_layout.addStretch(1)

        self.splitter.addWidget(self.left_scroll)

        # Right side: plots
        self.right_panel = QtWidgets.QWidget()
        self.right_layout = QtWidgets.QVBoxLayout(self.right_panel)
        self.right_layout.setContentsMargins(0, 0, 0, 0)
        self.right_layout.setSpacing(10)

        self.figure1 = Figure(figsize=(4, 2), dpi=100, layout="constrained")
        self.canvas1 = ResizableCanvas(self.figure1)
        self.canvas1.setSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.canvas1.setMinimumSize(0, 0)

        self.load_data = QtWidgets.QPushButton(parent=self.right_panel)
        self.load_data.setSizePolicy(
            QtWidgets.QSizePolicy.Policy.Maximum,
            QtWidgets.QSizePolicy.Policy.Fixed
        )
        self.load_data.setObjectName("load_data")

        self.figure2 = Figure(figsize=(4, 2), dpi=100, layout="constrained")
        self.canvas2 = ResizableCanvas(self.figure2)
        self.canvas2.setSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.canvas2.setMinimumSize(0, 0)

        self.canvas1.hide()
        self.canvas2.hide()

        self.export_data = QtWidgets.QPushButton(parent=self.right_panel)
        self.export_data.setSizePolicy(
            QtWidgets.QSizePolicy.Policy.Maximum,
            QtWidgets.QSizePolicy.Policy.Fixed
        )
        self.export_data.setObjectName("export_data")

        self.right_layout.addWidget(self.canvas1, 1)
        self.right_layout.addWidget(self.load_data, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.right_layout.addWidget(self.canvas2, 1)
        self.right_layout.addWidget(self.export_data, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.splitter.addWidget(self.right_panel)
        self.splitter.setStretchFactor(0, 1)
        self.splitter.setStretchFactor(1, 1)
        self.splitter.setSizes([620, 620])

        self.retranslateUi(MainWindow)
        self.bindButtons()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.metrics_title.setText(_translate("MainWindow", "Metrics"))

        self.ecg_title.setText(_translate("MainWindow", "ECG"))
        self.ecg_heartrate_title.setText(_translate("MainWindow", "Heartrate:"))
        self.ecg_heartrate_value.setText(_translate("MainWindow", "XX"))
        self.ecg_sqi_title.setText(_translate("MainWindow", "SQI:"))
        self.ecg_sqi_value.setText(_translate("MainWindow", "XX"))
        self.ecg_weight_title.setText(_translate("MainWindow", "Weight:"))
        self.ecg_weight_value.setText(_translate("MainWindow", "XX"))

        self.ppg_title.setText(_translate("MainWindow", "PPG"))
        self.ppg_heartrate_title.setText(_translate("MainWindow", "Heartrate:"))
        self.ppg_heartrate_value.setText(_translate("MainWindow", "XX"))
        self.ppg_sqi_title.setText(_translate("MainWindow", "SQI:"))
        self.ppg_sqi_value.setText(_translate("MainWindow", "XX"))
        self.ppg_weight_title.setText(_translate("MainWindow", "Weight:"))
        self.ppg_weight_value.setText(_translate("MainWindow", "XX"))

        self.fused_title.setText(_translate("MainWindow", "FUSED"))
        self.fhr_title.setText(_translate("MainWindow", "Fused Heartrate:"))
        self.fhr_value.setText(_translate("MainWindow", "XX"))
        self.fhrvsdnn_title.setText(_translate("MainWindow", "FHRV SDNN:"))
        self.fhrvsdnn_value.setText(_translate("MainWindow", "XX"))
        self.fhrvrmssd_title.setText(_translate("MainWindow", "FHRV RMSSD:"))
        self.fhrvrmssd_value.setText(_translate("MainWindow", "XX"))

        self.load_data.setText(_translate("MainWindow", "Load Data"))
        self.export_data.setText(_translate("MainWindow", "Export Data"))

    def bindButtons(self):
        self.load_data.clicked.connect(self.loadData)
        self.export_data.clicked.connect(self.exportData)

    def loadData(self):
        print("Loading Data")
        filepath, _ = QtWidgets.QFileDialog.getOpenFileName(
            self.centralwidget,
            "Select .npy data file",
            "",
            "NumPy files (*.npy)"
        )

        if not filepath:
            return

        filename = os.path.basename(filepath)
        patient_num = filename.split("_")[0]
        path = os.path.dirname(filepath)

        results = []
        print("Processing segment: ", 0)
        metrics, fig1, fig2 = process_segment_with_figure(path, patient_num, 0)
        results.append(metrics)

        for i in range(1, 30):
            print("Processing segment: ", i)
            metrics = process_segment(path, patient_num, i)
            results.append(metrics)

        if results:
            print("Calculating Values")
            mean_ecg_hr = round(np.mean([res['ecg_hr'] for res in results]))
            mean_ppg_hr = round(np.mean([res['ppg_hr'] for res in results]))
            mean_ecg_sqi = round(np.mean([res['ecg_sqi'] for res in results]),2)
            mean_ppg_sqi = round(np.mean([res['ppg_sqi'] for res in results]),2)
            mean_w_ecg = round(np.mean([res['ecg_weight'] for res in results]),2)
            mean_w_ppg = round(np.mean([res['ppg_weight'] for res in results]),2)
            mean_fused_hr = round(np.mean([res['fused_hr'] for res in results]))
            mean_fused_sdnn = round(np.mean([res['fused_sdnn'] for res in results]),2)
            mean_fused_rmssd = round(np.mean([res['fused_rmssd'] for res in results]),2)
        else:
            print("No results found")
            mean_ecg_hr = "XX"
            mean_ppg_hr = "XX"
            mean_ecg_sqi = "XX"
            mean_ppg_sqi = "XX"
            mean_w_ecg = "XX"
            mean_w_ppg = "XX"
            mean_fused_hr = "XX"
            mean_fused_sdnn = "XX"
            mean_fused_rmssd = "XX"

        self.ecg_heartrate_value.setText(str(mean_ecg_hr))
        self.ecg_sqi_value.setText(str(mean_ecg_sqi))
        self.ecg_weight_value.setText(str(mean_w_ecg))
        self.ppg_heartrate_value.setText(str(mean_ppg_hr))
        self.ppg_sqi_value.setText(str(mean_ppg_sqi))
        self.ppg_weight_value.setText(str(mean_w_ppg))
        self.fhr_value.setText(str(mean_fused_hr))
        self.fhrvsdnn_value.setText(str(mean_fused_sdnn))
        self.fhrvrmssd_value.setText(str(mean_fused_rmssd))

        self.plot(self.canvas1, fig1)
        self.plot(self.canvas2, fig2)
        self.canvas1.show()
        self.canvas2.show()

    def exportData(self):
        print("Exporting Data")

    def plot(self, canvas, fig):
        canvas.figure = fig
        fig.set_canvas(canvas)

        # Force the same resize behavior as manually resizing the window.
        event = QtGui.QResizeEvent(canvas.size(), canvas.size())
        canvas.resizeEvent(event)

        canvas.draw_idle()